service: ensure-aws-point-in-time-recovery-auto-enabler
custom:
  region: "${opt:region, 'eu-west-2'}"

provider:
  name: aws
  runtime: python3.8
  region: ${self:custom.region}
  environment:
    REGION: ${self:custom.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:ListTables
        - dynamodb:DescribeTable
        - dynamodb:UpdateContinuousBackups
        - dynamodb:DescribeContinuousbackups
      Resource: "arn:aws:dynamodb:${self:custom.region}:*:table/*"
functions:
  cron:
    handler: handler.run
    events:
      - schedule: rate(2 hours)
plugins:
  - serverless-python-requirements
